### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by Quenjy** [jfutoma/MGP-RNN#3]
Hello,

First of all, let me thank you for sharing your code.

I've been running it on my dataset and I can get it running, however my computer runs out of memory when dealing with particularly long patient stays (more than 200 hours with a grid time interval of 1 hour). For now I dealt with that by "cutting" earlier times for long stays.
But since I'm not experienced enough with tensorflow to answer this myself, I was wondering whether this memory limitation was unavoidable for this approach or whether it was some implementation problem? And if that is the case, do you know how this could be fixed?

Thanks

**Comment by jfutoma** [comment]
What is the dimensionality of your time series, and how much memory do you have?  In the current implementation it's going to be somewhat memory inefficient, since to sample from the MGP you need to construct rather large matrices.  The covariance matrix for a GP is n_times*n_vars, and this very quickly gets big for long series which is going to suck up memory.  Using the Lanczos method can help somewhat but it's still going to suck up a decent amount of memory and also slow down.  In practice I'd recommend filtering down very long time series; in practice I often do something like only use the last week of data (i.e. 24*7=168 hours).  

Hope this helps somewhat

**Comment by Quenjy** [comment]
Alright, thanks for your answer

I'll keep limiting the time series then, as far as the raw data is concerned, I'm working with multiple datasets with usually have between 20-40 tasks and the time series can go up to thousands of hours, so it's not too surpising
